Repository L3iyanin/ft_transcendence, pull requests merged in 2022-09, with the labels that each got.

#9 start making npm install in build time of container not in run time
  deployement/backend/Dockerfile
  deployement/backend/srcs/run.sh
  deployement/frontend/Dockerfile
  deployement/frontend/srcs/run.sh
  docker-compose.yaml
Labels: optimization

#8 fixed #7-database-volume-mounting
  .env.sample
  Makefile
  README.md
  docker-compose.yaml
  dockerCleanup.sh
Labels: optimization

#11 Adding dev mode: only database container
  Makefile
  README.md
  backend/.editorconfig
  backend/.env.sample
  backend/package-lock.json
  backend/package.json
  backend/prisma/schema.prisma
  docker-compose.yaml
Labels: bug, optimization

#15 add frontend strucure
  frontend/.editorconfig
  frontend/README.md
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.cjs
  frontend/public/logo.svg
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/components/LandingPage/TopSection.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/Landing.tsx
  frontend/src/routes/Router.tsx
  frontend/src/styles/global.scss
  frontend/src/styles/includes/_backgrounds.scss
  frontend/src/styles/includes/_buttons.scss
  frontend/src/styles/includes/_inputs.scss
  frontend/src/styles/includes/_typographies.scss
  frontend/tailwind.config.cjs
Labels: enhancement

#30 20 seven add 42 auth
  Makefile
  backend/.env.sample
  backend/.eslintrc.js
  backend/.prettierrc
  backend/README.md
  backend/nest-cli.json
  backend/package-lock.json
  backend/package.json
  backend/prisma/dropDatabase.ts
  backend/prisma/schema.prisma
  backend/prisma/seed.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.interface.ts
  backend/src/auth/auth.service.ts
  backend/src/main.ts
Labels: backend

#46 added i18n
  backend/.eslintrc.js
  backend/.gitignore
  backend/.prettierrc
  backend/nest-cli.json
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/i18n/ar/translations.json
  backend/src/i18n/en/translations.json
  backend/src/i18n/ti/translations.json
  backend/src/users/user.guard.ts
  backend/src/users/user.interface.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.ts
Labels: backend

#51 23 kirwa create chat page
  frontend/package-lock.json
  frontend/package.json
  frontend/public/imgs/icons/muchi-muchi.png
  frontend/src/assets/icons/play.svg
  frontend/src/assets/icons/profile.svg
  frontend/src/components/Pages/Chat/ChatActions.tsx
  frontend/src/components/Pages/Chat/ConversationCard.tsx
  frontend/src/components/Pages/Chat/ConversationsList.tsx
  frontend/src/components/Pages/Chat/MessageCard.tsx
  frontend/src/components/Pages/Chat/MessagesList.tsx
  frontend/src/components/Pages/Game/WatchersAndPlayers/PlayerCard.tsx
  frontend/src/components/Pages/Game/WatchersAndPlayers/WatchersList.tsx
  frontend/src/components/UI/Buttons/ButtonWithIcon.tsx
  frontend/src/components/UI/inputs/Input.tsx
  frontend/src/components/UI/inputs/InputWithIcon.tsx
  frontend/src/i18n/locales/en/translations.json
  frontend/src/pages/Chat.tsx
  frontend/src/utils/data/Chat.ts
  frontend/src/utils/data/GamePage.ts
  frontend/src/utils/data/Users.ts
  frontend/src/utils/helper/messageHelper.ts
  frontend/src/utils/types/Chat.d.ts
Labels: Fontend

#58 54 kirwa create channel option of chat
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/icons/add.svg
  frontend/src/assets/icons/cog.svg
  frontend/src/assets/icons/shield.svg
  frontend/src/components/Pages/Chat/ChatActions.tsx
  frontend/src/components/Pages/Chat/ConversationCard.tsx
  frontend/src/components/Pages/Chat/ConversationsList.tsx
  frontend/src/components/Pages/Chat/CreateChannelPopup.tsx
  frontend/src/components/Pages/Chat/DiscussionSection.tsx
  frontend/src/components/Pages/Chat/MessageCard.tsx
  frontend/src/components/Pages/Chat/MessagesList.tsx
  frontend/src/components/UI/Alerts/Alert.tsx
  frontend/src/components/UI/Buttons/ButtonWithIcon.tsx
  frontend/src/components/UI/Modals/Modal.tsx
  frontend/src/components/UI/RoundedFilter.tsx
  frontend/src/hooks/useBotChannel.tsx
  frontend/src/i18n/locales/ar/translations.json
  frontend/src/i18n/locales/en/translations.json
  frontend/src/pages/Chat.tsx
  frontend/src/utils/constants/enum.ts
  frontend/src/utils/data/Chat.ts
  frontend/src/utils/types/Chat.d.ts
Labels: Fontend
